// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function CancelOAuthLogin():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_OAuthCancelResult_>;

export function CompleteOAuthLogin():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountsSnapshot_>;

export function DeleteAccount(arg1:string):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountsSnapshot_>;

export function GetAccountUsage(arg1:string):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountUsageSnapshot_>;

export function GetProcessStatus():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_ProcessStatus_>;

export function LoadAccounts():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountsSnapshot_>;

export function LoadBootstrap():Promise<contracts.BootstrapPayload>;

export function RefreshAllUsage():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_UsageCollection_>;

export function RenameAccount(arg1:contracts.RenameAccountInput):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountsSnapshot_>;

export function StartOAuthLogin(arg1:contracts.StartOAuthLoginInput):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_OAuthLoginInfo_>;

export function SwitchAccount(arg1:contracts.SwitchAccountInput):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_SwitchAccountResult_>;

export function WarmupAccount(arg1:string):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_WarmupAccountResult_>;

export function WarmupAllAccounts():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_WarmupAllResult_>;
