// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function LoadBootstrap():Promise<contracts.BootstrapPayload>;
