// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOAuthLogin() {
  return window['go']['main']['App']['CancelOAuthLogin']();
}

export function CompleteOAuthLogin() {
  return window['go']['main']['App']['CompleteOAuthLogin']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccountUsage(arg1) {
  return window['go']['main']['App']['GetAccountUsage'](arg1);
}

export function GetProcessStatus() {
  return window['go']['main']['App']['GetProcessStatus']();
}

export function LoadAccounts() {
  return window['go']['main']['App']['LoadAccounts']();
}

export function LoadBootstrap() {
  return window['go']['main']['App']['LoadBootstrap']();
}

export function LoadWarmupScheduleStatus() {
  return window['go']['main']['App']['LoadWarmupScheduleStatus']();
}

export function RefreshAllUsage() {
  return window['go']['main']['App']['RefreshAllUsage']();
}

export function RenameAccount(arg1) {
  return window['go']['main']['App']['RenameAccount'](arg1);
}

export function SaveWarmupSchedule(arg1) {
  return window['go']['main']['App']['SaveWarmupSchedule'](arg1);
}

export function StartOAuthLogin(arg1) {
  return window['go']['main']['App']['StartOAuthLogin'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function WarmupAccount(arg1) {
  return window['go']['main']['App']['WarmupAccount'](arg1);
}

export function WarmupAllAccounts() {
  return window['go']['main']['App']['WarmupAllAccounts']();
}
