// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function DeleteAccount(arg1:string):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountsSnapshot_>;

export function GetProcessStatus():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_ProcessStatus_>;

export function LoadAccounts():Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountsSnapshot_>;

export function LoadBootstrap():Promise<contracts.BootstrapPayload>;

export function RenameAccount(arg1:contracts.RenameAccountInput):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_AccountsSnapshot_>;

export function SwitchAccount(arg1:contracts.SwitchAccountInput):Promise<contracts.ResultEnvelope_codex_switch_internal_contracts_SwitchAccountResult_>;
