// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetProcessStatus() {
  return window['go']['main']['App']['GetProcessStatus']();
}

export function LoadAccounts() {
  return window['go']['main']['App']['LoadAccounts']();
}

export function LoadBootstrap() {
  return window['go']['main']['App']['LoadBootstrap']();
}

export function RenameAccount(arg1) {
  return window['go']['main']['App']['RenameAccount'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}
